name = "r4300"
#compiler = { git = "https://gitlab.com/spade-lang/spade.git", branch = "main" }
compiler = { git = "https://gitlab.com/spade-lang/spade", branch = "namespace-diagnostic" }

[simulation]
testbench_dir = "test"